---
version: '3'
services:

  #PHP Service
  app:
    build:
      context: ../../
      dockerfile: docker/php/base/Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../../:/var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8086:80"
      - "4463:443"
    volumes:
      - ../../:/var/www
      - ../nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  postgres:
    # https://hub.docker.com/_/postgres?tab=tags&page=1&name=12.4
    image: postgres:15.0-alpine
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: database
    ports:
      - $PROJECT_IP:${DOCKER_PORT_POSTGRES:-5432}:5432
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
